### ISSUE TITLE
delete a node from linked list

### ISSUE THREAD

**Issue by ayushjindal23** [ajitkumar1264/Algorithms#147]
Can you assign it to me? @ajitkumar1264

**Comment by ayushjindal23** [comment]
Please assign this to me under Hacktoberfest2022 .

**Comment by Tanya401** [comment]
Could you please assign this to me under Hacktoberfest 2022 label. Thank you.

**Comment by utkarshsingx** [comment]
Could you please assign this to me under Hacktober fest 2022 label. Thank you.

**Comment by Pallavibahekar** [comment]
Please can you assign me this issue.
I believe I'll be able to make a good contribution

**Comment by ayushjindal23** [comment]
Hi, @ajitkumar1264  I would like to contribute to this repo and add a program for the deletion of nodes in a linked list in C++.
Please assign this to me under Hacktoberfest2022.
Thanks!!
