### ISSUE TITLE
Stack using Linked List

### ISSUE THREAD

**Issue by VarunBhattacharya** [ajitkumar1264/Algorithms#205]
Implementation of Stack using Linked List Data Structure.

**Comment by suraj-s13** [comment]
plz assign me this task.

**Comment by VarunBhattacharya** [comment]
I have completed it

**Comment by Satorusimpp** [comment]
Kindly assign me to this issue.

**Comment by hussainiftikhar5242** [comment]
Hi Buddy @VarunBhattacharya, Can you plz assign this issue to me.

**Comment by VarunBhattacharya** [comment]
the work is already completed.
