### ISSUE TITLE
snake game

### ISSUE THREAD

**Issue by megha-vishwakarma** [ajitkumar1264/Algorithms#21]
I would like to make a Snake game in java

Expected behavior
•Snake can move in a given direction and when it eats the food, the length of snake increases. 
• When snake crosses itself, the game will over. 
• Food will be generated at a given interval.

Additional context (optional )
Assign me this issue under hactoberfest @ajitkumar1264

**Comment by ajitkumar1264** [comment]
ok, you can work on it 👍.

**Comment by megha-vishwakarma** [comment]
Thank you so very much @ajitkumar1264

**Comment by suraj-s13** [comment]
I would like to make a snake game in python.

Expected behaviors:-
1.Snake can move in a given direction and when it eats the food, the length of snake increases.
2.When snake crosses itself or touches any walls, the game will over.
3.Food will be generated at a given interval.

Please Assign me this issue under hactoberfes @suraj-s13

**Comment by megha-vishwakarma** [comment]
Hello  @suraj-s13 , You can create  tic-tac teo game,Puzzle Game, Ping Pong Game and many more I have raise the issue ask Ajit to assign you ,

**Comment by suraj-s13** [comment]
ok @megha-vishwakarma
