### ISSUE TITLE
Tic Tac Toe Game in Java

### ISSUE THREAD

**Issue by megha-vishwakarma** [ajitkumar1264/Algorithms#73]
Create a Tic-Tac-Toe game 

Expected behaviors :
The Tic-Tac-Toe game is also called the X and O game. The player who succeeds in placing their marks in a diagonal, horizontal, or vertical row is the winner.

**Comment by suraj-s13** [comment]
I would like to make a tic-tac-tor game in java.

Expected behaviors:-
1.You are X, your friend (or the computer in this case) is O. Players take turns putting their marks in empty squares
2.The first player to get 3 of her marks in a row (up, down, across, or diagonally) is the winner.

Please Assign me this issue under hactoberfest @suraj-s13

**Comment by ajitkumar1264** [comment]
if have you completed so mention your pr here.

**Comment by suraj-s13** [comment]
completed issue #73
