### ISSUE TITLE
Operations on Stack

### ISSUE THREAD

**Issue by VarunBhattacharya** [ajitkumar1264/Algorithms#83]
Implementation of various operations on the stack.

**Comment by suraj-s13** [comment]
I will create a readme file with full explanation and images to understand the implementation of stack oprations with code and output.

Assign me for this task @suraj-s13

**Comment by rohan1888** [comment]
I will implement all the stack operations in C.....  Assign me this task

**Comment by VarunBhattacharya** [comment]
I have already completed it.

**Comment by ajitkumar1264** [comment]
if have you completed so mention your pr here @suraj-s13 .

**Comment by rohan1888** [comment]
Okk i will

**Comment by suraj-s13** [comment]
completed issue #83
